// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHCsUB9BFCEJCxD5mSdGmoztovIMCv9ik',
    appId: '1:102698365620:web:560561d3f834b6fdfd9de1',
    messagingSenderId: '102698365620',
    projectId: 'book-it-now25',
    authDomain: 'book-it-now25.firebaseapp.com',
    storageBucket: 'book-it-now25.firebasestorage.app',
    measurementId: 'G-DWWYD77SB8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjsihuN-9UrfspLF00Zw64suA42_YdFkY',
    appId: '1:102698365620:android:71537a02d2f1af9afd9de1',
    messagingSenderId: '102698365620',
    projectId: 'book-it-now25',
    storageBucket: 'book-it-now25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5olw31nufjSDCinYjAacXErtbOhmjgYI',
    appId: '1:102698365620:ios:734ac7c129bd7deffd9de1',
    messagingSenderId: '102698365620',
    projectId: 'book-it-now25',
    storageBucket: 'book-it-now25.firebasestorage.app',
    iosBundleId: 'com.example.projectTesting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5olw31nufjSDCinYjAacXErtbOhmjgYI',
    appId: '1:102698365620:ios:734ac7c129bd7deffd9de1',
    messagingSenderId: '102698365620',
    projectId: 'book-it-now25',
    storageBucket: 'book-it-now25.firebasestorage.app',
    iosBundleId: 'com.example.projectTesting',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHCsUB9BFCEJCxD5mSdGmoztovIMCv9ik',
    appId: '1:102698365620:web:d0f9d435ca85f1cdfd9de1',
    messagingSenderId: '102698365620',
    projectId: 'book-it-now25',
    authDomain: 'book-it-now25.firebaseapp.com',
    storageBucket: 'book-it-now25.firebasestorage.app',
    measurementId: 'G-YL83HWM8L5',
  );

}